src/Entity/Item.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 */
class Item
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $itemLevel;

    /**
     * @ORM\Column(type="integer")
     */
    private $requiredLevel;

    /**
     * @ORM\Column(type="integer")
     */
    private $quality;

    /**
     * @ORM\Column(type="datetime")
     */
    private $lastImport;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(nullable=false)
     */
    private $class;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SubCategory")
     * @ORM\JoinColumn(nullable=false)
     */
    private $subClass;

    /**
     * @ORM\Column(type="integer")
     */
    private $classFromWH;

    /**
     * @ORM\Column(type="integer")
     */
    private $subClassFromWH;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Loot", mappedBy="item")
     */
    private $loots;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_de;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $inventorySlot;

    /**
     * @ORM\ManyToOne(targetEntity=Zone::class, inversedBy="items")
     */
    private $zone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hidden;

    public function __construct()
    {
        $this->loots = new ArrayCollection();
        $this->zone = new ArrayCollection();
    }

    public function __toString()
    {
        return (string)$this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getItemLevel(): ?int
    {
        return $this->itemLevel;
    }

    public function setItemLevel(int $itemLevel): self
    {
        $this->itemLevel = $itemLevel;

        return $this;
    }

    public function getRequiredLevel(): ?int
    {
        return $this->requiredLevel;
    }

    public function setRequiredLevel(int $requiredLevel): self
    {
        $this->requiredLevel = $requiredLevel;

        return $this;
    }

    public function getQuality(): ?int
    {
        return $this->quality;
    }

    public function setQuality(int $quality): self
    {
        $this->quality = $quality;

        return $this;
    }

    public function getLastImport(): ?DateTimeInterface
    {
        return $this->lastImport;
    }

    public function setLastImport(DateTimeInterface $lastImport): self
    {
        $this->lastImport = $lastImport;

        return $this;
    }

    public function getClass(): ?Category
    {
        return $this->class;
    }

    public function setClass(?Category $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getSubClass(): ?SubCategory
    {
        return $this->subClass;
    }

    public function setSubClass(?SubCategory $subClass): self
    {
        $this->subClass = $subClass;

        return $this;
    }

    public function getClassFromWH(): ?int
    {
        return $this->classFromWH;
    }

    public function setClassFromWH(int $classFromWH): self
    {
        $this->classFromWH = $classFromWH;

        return $this;
    }

    public function getSubClassFromWH(): ?int
    {
        return $this->subClassFromWH;
    }

    public function setSubClassFromWH(int $subClassFromWH): self
    {
        $this->subClassFromWH = $subClassFromWH;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Loot[]
     */
    public function getLoots(): Collection
    {
        return $this->loots;
    }

    public function addLoot(Loot $loot): self
    {
        if (!$this->loots->contains($loot)) {
            $this->loots[] = $loot;
            $loot->setItem($this);
        }

        return $this;
    }

    public function removeLoot(Loot $loot): self
    {
        if ($this->loots->contains($loot)) {
            $this->loots->removeElement($loot);
            // set the owning side to null (unless already changed)
            if ($loot->getItem() === $this) {
                $loot->setItem(null);
            }
        }

        return $this;
    }

    public function getNameDe(): ?string
    {
        return $this->name_de;
    }

    public function setNameDe(?string $name_de): self
    {
        $this->name_de = $name_de;

        return $this;
    }

    public function getInventorySlot(): ?int
    {
        return $this->inventorySlot;
    }

    public function setInventorySlot(?int $inventorySlot): self
    {
        $this->inventorySlot = $inventorySlot;

        return $this;
    }

    public function getZone(): ?Zone
    {
        return $this->zone;
    }

    public function setZone(?Zone $zone): self
    {
        $this->zone = $zone;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    public function getAbbreviation()
    {
        $shortName = [];
        $parts = explode(' ', $this->name);
        foreach ($parts as $part) {
            $shortName[] = substr($part, 0, 1);
        }
        return implode('', $shortName);
    }

    public function getHidden(): ?bool
    {
        return $this->hidden;
    }

    public function setHidden(bool $hidden): self
    {
        $this->hidden = $hidden;

        return $this;
    }
}

src/Controller/CharacterController.php
<?php

namespace App\Controller;

use App\Entity\Attendance;
use App\Entity\Character;
use App\Entity\CharacterLootRequirement;
use App\Entity\Raid;
use App\Entity\Recipe;
use App\Form\CharacterType;
use App\Repository\CharacterLootRequirementRepository;
use App\Repository\CharacterRepository;
use App\Repository\ItemRepository;
use App\Repository\LootRepository;
use App\Repository\RecipeRepository;
use App\Utility\WowClassUtility;
use App\Utility\WowProfessionUtility;
use App\Utility\WowRaceUtility;
use App\Utility\WowSlotUtility;
use App\Utility\WowSpecUtility;
use App\Utility\WoWZoneUtility;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class CharacterController extends AbstractController
{
    /**
     * @var CharacterRepository
     */
    private $characterRepository;
    /**
     * @var LootRepository
     */
    private $lootRepository;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var CharacterLootRequirementRepository
     */
    private $lootRequirementRepository;
    /**
     * @var ItemRepository
     */
    private $itemRepository;
    /**
     * @var RecipeRepository
     */
    private $recipeRepository;

    public function __construct(
        CharacterRepository $characterRepository,
        LootRepository $lootRepository,
        CharacterLootRequirementRepository $lootRequirementRepository,
        ItemRepository $itemRepository,
        RecipeRepository $recipeRepository,
        EntityManagerInterface $entityManager)
    {
        $this->characterRepository = $characterRepository;
        $this->lootRepository = $lootRepository;
        $this->lootRequirementRepository = $lootRequirementRepository;
        $this->itemRepository = $itemRepository;
        $this->recipeRepository = $recipeRepository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/roster", name="roster")
     * @return Response
     */
    public function indexAction(): Response
    {
        $roster = [];
        $fullRoster = $this->characterRepository->findAll();
        foreach ($fullRoster as $item) {
            $roster[$item->getClass()][] = $item;
        }
        return $this->render('character/index.html.twig', ['roster' => $roster]);
    }

    /**
     * @Route("/roster/recipes/{subClass?}", name="roster_recipe")
     * @param $subClass
     * @return Response
     */
    public function recipeAction($subClass): Response
    {
        $recipes = false;
        $categories = $this->recipeRepository->findRecipeCategories();
        if ($subClass) {
            $recipes = $this->recipeRepository->findByCategory($subClass);
        }
        return $this->render('character/recipes.html.twig', [
            'categories' => $categories,
            'subClass' => $subClass,
            'recipes' => $recipes
        ]);
    }

    /**
     * @Route("/character/{charId}", name="character")
     * @param int $charId
     * @param WowProfessionUtility $wowProfessionUtility
     * @param WoWZoneUtility $woWZoneUtility
     * @return Response
     */
    public function characterDetailsAction(int $charId, WowProfessionUtility $wowProfessionUtility, WoWZoneUtility $woWZoneUtility): Response
    {
        $raids = [];
        $char = $this->characterRepository->find($charId);
        if (!$char) {
            return new Response('Char not found', 404);
        }
        foreach ($char->getAttendances() as $attendance) {
            $raids[] = $this->compileRaidData($attendance);
        }
        $needsItemsFromZones = $this->lootRequirementRepository->findItemsByCharId($charId);
        return $this->render('character/detail.html.twig', [
            'character' => $char,
            'raids' => $raids,
            'professions' => $wowProfessionUtility,
            'zones' => $woWZoneUtility,
            'itemsByZone' => $needsItemsFromZones
        ]);
    }

    /**
     * @Route("/profile/characters", name="profile_character")
     * @param WowClassUtility $wowClassUtility
     * @param WowSpecUtility $wowSpecUtility
     * @param WowRaceUtility $wowRaceUtility
     * @return Response
     */
    public function myCharactersAction(WowClassUtility $wowClassUtility, WowSpecUtility $wowSpecUtility, WowRaceUtility $wowRaceUtility): Response
    {
        $characters = $this->characterRepository->findBy(['account' => $this->getUser()]);

        return $this->render('user/my_characters.html.twig', [
            'characters' => $characters,
            'raceUtility' => $wowRaceUtility,
            'specUtility' => $wowSpecUtility,
            'classUtility' => $wowClassUtility
        ]);
    }

    /**
     * @Route("/characters/create", name="character_create")
     * @param Request $request
     * @param TranslatorInterface $translator
     * @return Response
     */
    public function createAction(Request $request, TranslatorInterface $translator): Response
    {
        $character = new Character();
        $form = $this->createForm(CharacterType::class, $character);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $exists = $this->characterRepository->findOneBy(['name' => $character->getName()]);
            if (null === $exists) {
                $character->setAccount($this->getUser());
                $this->entityManager->persist($character);
                $this->entityManager->flush();

                $this->addFlash('success', $translator->trans('Character saved.'));

                return $this->redirectToRoute('profile_character');
            }

            $this->addFlash('danger', $translator->trans('That character name is already taken.'));
        }

        return $this->render('loot_requirement/form.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/character/{charId}/update", name="character_update")
     * @param int $charId
     * @param Request $request
     * @return Response
     */
    public function updateAction(int $charId, Request $request): Response
    {
        $character = $this->characterRepository
        ->findOneBy(['account' => $this->getUser(), 'id' => $charId]);

        if (null === $character) {
            return $this->redirectToRoute('character_create');
        }

        $form = $this->createForm(CharacterType::class, $character);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $exists = $this->characterRepository->findOneBy(['name' => $character->getName()]);
            if (null === $exists || $exists->getId() === $character->getId()) {
                $character->setAccount($this->getUser());
                $this->entityManager->persist($character);
                $this->entityManager->flush();

                $this->addFlash('success', 'Character saved.');

                return $this->redirectToRoute('profile_character');
            }

            $this->addFlash('danger', 'That character name is already taken.');
        }

        /**
         * Add recipes
         */
        $recipe = $request->get('recipe');
        if (isset($recipe['itemId'])) {
            $recipeItem = $this->itemRepository->find((int)$recipe['itemId']);
            if ($recipeItem !== null) {
                $checkIfEntryExists = $this->recipeRepository->findBy(
                    [
                        'Player' => $character->getId(),
                        'recipe' => $recipeItem
                    ]
                );
                if (count($checkIfEntryExists) === 0) {
                    $entry = new Recipe();
                    $entry->setPlayer($character);
                    $entry->setRecipe($recipeItem);
                    $character->addRecipe($entry);
                    $this->entityManager->persist($entry);
                    $this->entityManager->persist($character);
                    $this->entityManager->flush();
                    $this->addFlash('success', 'Added recipe ' . $recipeItem->getName());
                return $this->redirectToRoute('character_update', ['charId' => $character->getId()]);
                }
            }
        }

        /**
         * Remove Recipes
         */
        $removeRecipeId = $request->get('removeRecipeId');
        if ($removeRecipeId !== null) {
            $recipeItem = $this->recipeRepository->find((int)$removeRecipeId);
            if ($recipeItem !== null) {
                $this->entityManager->remove($recipeItem);
                $this->entityManager->flush();
                $this->addFlash('success', 'Removed recipe ' . $recipeItem->getRecipe()->getName());
            }
        }
        return $this->render(
            'loot_requirement/form.html.twig',
            [
                'form' => $form->createView(),
                'character' => $character
            ]
        );
    }

    /**
     * @Route("/character/{charId}/bislist/{slotId?}", name="character_bislist")
     *
      * @param int $charId
     * @param int $slotId
     * @param WowSlotUtility $wowSlotUtility
     * @return Response
     */
    public function bisListViewAction(int $charId, $slotId, WowSlotUtility $wowSlotUtility): Response
    {
        $character = $this->characterRepository->find($charId);
        $items = $this->lootRequirementRepository->findBy([
            'playerCharacter' => $character,
        ]);
        $bisItems = [];
        foreach ($wowSlotUtility::toArray() as $slotIdFromUtility => $_) {
            $bisItems[$slotIdFromUtility] = [
                1 => null,
                2 => null,
                21 => null,
                22 => null,
                31 => null,

templates/character/bis_list.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/macros.html.twig' as macros %}
{% block title %}{% trans %}BiS for{% endtrans %} {{ character.name }}{% endblock %}

{% block body %}
    <div class="content-section bg-transparent">
        <div class="container-fluid">
            <p><a class="btn btn-outline-primary" href="https://wowtbc.gg/bis-list/balance-druid/" target="_blank">{% trans %}BiS Gear Planner{% endtrans %}</a></p>
            <hr>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-3">
                    <h3>{{ character.name }}</h3>
                    <ul class="list-group">
                        {% for slotIdFromUtility, slotName in slotUtility.toArray %}
                            {{ macros.bisSelection(character.id, slotIdFromUtility, slotId, slotUtility, bisItems, wowheaddomain)}}
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-9">
                    <p>Tragt in die Phasen ein, was in den Phasen <u>jeweils</u> droppt. Also Loot aus P1 auch in P1 lassen.</p>
                    <p>Bitte keine Items 2x eintragen, die ihr nicht auch 2x tragen könnt.</p>
                    {% if slotId == '' %}
                        <h1>{% trans %}Please select a slot{% endtrans %}</h1>
                    {% else %}
                        <form action="{{ path('save_bis', {charId: character.id, slot: slotId}) }}" method="post">
                        <h3 id="slots" data-slotids="{{ slotId }}">{{ slotUtility.slotName(slotId) }}</h3>
                        <h4>Phase 1 (Karazhan, Gruul's Lair, Magtheridon's Lair)</h4>
                        <div class="card-deck">
                            {{ macros.itemDisplay(1, bisItems[slotId].1, slotId, character.id, wowheaddomain) }}
                            {{ macros.itemDisplay(2, bisItems[slotId].2, slotId, character.id, wowheaddomain) }}
                            {% if slotId == 11 or slotId == 12 %}
                                {{ macros.itemDisplay(3, bisItems[slotId].3, slotId, character.id, wowheaddomain) }}
                                {{ macros.itemDisplay(4, bisItems[slotId].4, slotId, character.id, wowheaddomain) }}
                            {% endif %}
                        </div>
                        <hr>
                        <h4>Phase 2 (Serpentshrine, Tempest Keep)</h4>
                        <div class="card-deck">
                            {{ macros.itemDisplay(21, bisItems[slotId].21, slotId, character.id, wowheaddomain) }}
                            {{ macros.itemDisplay(22, bisItems[slotId].22, slotId, character.id, wowheaddomain) }}
                            {% if slotId == 11 or slotId == 12 %}
                                {{ macros.itemDisplay(23, bisItems[slotId].23, slotId, character.id, wowheaddomain) }}
                                {{ macros.itemDisplay(24, bisItems[slotId].24, slotId, character.id, wowheaddomain) }}
                            {% endif %}
                        </div>
                        <hr>
                        <h4>Phase 3 (Mount Hyjal, Black Temple)</h4>
                        <div class="card-deck">
                            {{ macros.itemDisplay(31, bisItems[slotId].31, slotId, character.id, wowheaddomain) }}
                            {{ macros.itemDisplay(32, bisItems[slotId].32, slotId, character.id, wowheaddomain) }}
                            {% if slotId == 11 or slotId == 12 %}
                                {{ macros.itemDisplay(33, bisItems[slotId].33, slotId, character.id, wowheaddomain) }}
                                {{ macros.itemDisplay(34, bisItems[slotId].34, slotId, character.id, wowheaddomain) }}
                            {% endif %}
                        </div>
                        <hr>
                        <h4>Phase 4 (Zul'Aman)</h4>
                        <div class="card-deck">
                            {{ macros.itemDisplay(41, bisItems[slotId].41, slotId, character.id, wowheaddomain) }}
                            {{ macros.itemDisplay(42, bisItems[slotId].42, slotId, character.id, wowheaddomain) }}
                            {% if slotId == 11 or slotId == 12 %}
                                {{ macros.itemDisplay(43, bisItems[slotId].43, slotId, character.id, wowheaddomain) }}
                                {{ macros.itemDisplay(44, bisItems[slotId].44, slotId, character.id, wowheaddomain) }}
                            {% endif %}
                        </div>
                        <hr>
                        <h4>Phase 5 (Sunwell)</h4>
                        <div class="card-deck">
                            {{ macros.itemDisplay(51, bisItems[slotId].51, slotId, character.id, wowheaddomain) }}
                            {{ macros.itemDisplay(52, bisItems[slotId].52, slotId, character.id, wowheaddomain) }}
                            {% if slotId == 11 or slotId == 12 %}
                                {{ macros.itemDisplay(53, bisItems[slotId].53, slotId, character.id, wowheaddomain) }}
                                {{ macros.itemDisplay(54, bisItems[slotId].54, slotId, character.id, wowheaddomain) }}
                            {% endif %}
                        </div>
                        <hr>
                        <input type="submit" class="btn btn-success" value="{% trans %}Save{% endtrans %}">
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/character/detail.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/macros.html.twig' as macros %}

{% block title %}{{character.name}}{% endblock %}

{% block body %}
    <div class="content-section bg-primary text-white">
        <div class="container">
            <h1>
                <span class="wow-class-icon"><img class="rounded" src="/assets/icons/class_{{ character.class }}.png" width="44" height="44" /></span>
                <span class="class-spec">
                            {% if character.metaSpec == 1 %}
                                <i class="fa fa-fw fa-shield-alt"></i>
                            {% elseif character.metaSpec == 2 %}
                                <i class="fa fa-fw fa-band-aid"></i>
                            {% elseif character.metaSpec == 3 %}
                                <i class="fa fa-fw fa-skull-crossbones"></i>
                            {% elseif character.metaSpec == 4 %}
                                <i class="fa fa-fw fa-crosshairs"></i>
                            {% endif %}
                            </span>
                {{character.name}} {{ character.note }}
            </h1>
        </div>
    </div>
    <div class="content-section bg-transparent">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h3>Professions</h3>
                    <h5>{{ professions.professionName(character.profession1) }}</h5>
                    {{ macros.professions(character.profession1skill) }}
                    <h5 class="mt-4">{{ professions.professionName(character.profession2) }}</h5>
                    {{ macros.professions(character.profession2skill) }}
                </div>
                <div class="col-sm-5">
                    <h3>Needs Items from</h3>
                    <ul class="list-group list-group-flush">
                        {% for zoneId, items in itemsByZone %}
                            <li class="list-group-item"><a href="{{ path('bis_need_by_zone', {'zoneId': zoneId}) }}">{{ zones.zoneName(zoneId) }}</a><br>
                                <small>
                                    {% for item in items %}
                                        <a href="https://{{wowheaddomain}}.wowhead.com/item={{ item.id }}" target="wowhead" data-wowhead="item={{ item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="small">
                                            {% if wowheaddomain == 'de.classic' %}
                                                {{ item.nameDe }}
                                            {% else %}
                                                {{ item.name }}
                                            {% endif %}
                                        </a><br>
                                    {% endfor %}
                                </small>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-sm-4">
                    <h3>{% trans %}Known Recipes{% endtrans %}</h3>
                    <ul class="list-group">
                        {% for recipe in character.recipes %}
                            <li class="list-group-item"><a href="#" data-wowhead="item={{ recipe.recipe.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="small">{{ recipe.recipe.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-6">
                    <h3>{% trans %}Raid Attendance{% endtrans %}</h3>
                    <table class="table table-sm">
                        <tr>
                            <th>{% trans %}Note{% endtrans %}</th>
                            <th>{% trans %}Date{% endtrans %}</th>
                            <th>{% trans %}Loots{% endtrans %}</th>
                        </tr>
                        {% for attended in raids %}
                            <tr>
                                <td><a href="{{ path('raid_show', {'raidId': attended.raid.id}) }}">{{ attended.raid.note }}</td>
                                <td>{{ attended.raid.date|date('d.m.Y') }}</td>
                                <td>
                                    {% for loot in attended.loots %}
                                        <span class="guildbank-item-icon">
                                    <a href="#" data-wowhead="item={{ loot.item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="medium"></a>
                                </span>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="col-sm-6">
                    <h3>{% trans %}Loot{% endtrans %}</h3>
                    <ul class="list-group">
                        {% for loot in character.loots %}
                            <li class="list-group-item">
                                <span class="guildbank-item-icon">
                                    <a href="#" data-wowhead="item={{ loot.item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="medium"></a>
                                </span>
                                {{ loot.item.name }} > <a href="{{ path('raid_show', {'raidId': loot.raid.id}) }}">{{ loot.raid.note }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/character/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Character{% endtrans %}{% endblock %}

{% block body %}
    <div class="content-section bg-transparent">
        <div class="container">
            <h3>{% trans %}Character{% endtrans %}</h3>
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/character/recipes.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/macros.html.twig' as macros %}

{% block title %}{% trans %}Raid Recipes{% endtrans %}{% endblock %}

{% block body %}
    <div class="content-section bg-primary text-white">
        <div class="container">
            <h1>{% trans %}Raid Recipes{% endtrans %}</h1>
        </div>
    </div>
    <div class="content-section bg-transparent">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <h5>{% trans %}Category{% endtrans %}</h5>
                    <div class="list-group">
                        {% for category in categories %}
                            <a class="list-group-item list-group-item-action{% if category.id == subClass %} active{% endif %}" href="{{ path('roster_recipe', {subClass: category.id}) }}">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-9">
                    {% if recipes is defined %}
                        <h5>{% trans %}Players with Recipes{% endtrans %}</h5>
                        <ul class="list-group">
                            {% for recipe in recipes %}
                                <li class="list-group-item">
                                    <a href="#" data-wowhead="item={{ recipe.recipe.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="medium">{{ recipe.recipe.name }}</a>
                                    <br>
                                        <small>
                                            {% for player in recipe.players %}
                                                {{ player.name }}{% if not loop.last %},{% endif %}
                                            {% endfor %}
                                        </small><br>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}