src/Entity/Item.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 */
class Item
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $itemLevel;

    /**
     * @ORM\Column(type="integer")
     */
    private $requiredLevel;

    /**
     * @ORM\Column(type="integer")
     */
    private $quality;

    /**
     * @ORM\Column(type="datetime")
     */
    private $lastImport;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(nullable=false)
     */
    private $class;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SubCategory")
     * @ORM\JoinColumn(nullable=false)
     */
    private $subClass;

    /**
     * @ORM\Column(type="integer")
     */
    private $classFromWH;

    /**
     * @ORM\Column(type="integer")
     */
    private $subClassFromWH;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Loot", mappedBy="item")
     */
    private $loots;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_de;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $inventorySlot;

    /**
     * @ORM\ManyToOne(targetEntity=Zone::class, inversedBy="items")
     */
    private $zone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hidden;

    public function __construct()
    {
        $this->loots = new ArrayCollection();
        $this->zone = new ArrayCollection();
    }

    public function __toString()
    {
        return (string)$this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getItemLevel(): ?int
    {
        return $this->itemLevel;
    }

    public function setItemLevel(int $itemLevel): self
    {
        $this->itemLevel = $itemLevel;

        return $this;
    }

    public function getRequiredLevel(): ?int
    {
        return $this->requiredLevel;
    }

    public function setRequiredLevel(int $requiredLevel): self
    {
        $this->requiredLevel = $requiredLevel;

        return $this;
    }

    public function getQuality(): ?int
    {
        return $this->quality;
    }

    public function setQuality(int $quality): self
    {
        $this->quality = $quality;

        return $this;
    }

    public function getLastImport(): ?DateTimeInterface
    {
        return $this->lastImport;
    }

    public function setLastImport(DateTimeInterface $lastImport): self
    {
        $this->lastImport = $lastImport;

        return $this;
    }

    public function getClass(): ?Category
    {
        return $this->class;
    }

    public function setClass(?Category $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getSubClass(): ?SubCategory
    {
        return $this->subClass;
    }

    public function setSubClass(?SubCategory $subClass): self
    {
        $this->subClass = $subClass;

        return $this;
    }

    public function getClassFromWH(): ?int
    {
        return $this->classFromWH;
    }

    public function setClassFromWH(int $classFromWH): self
    {
        $this->classFromWH = $classFromWH;

        return $this;
    }

    public function getSubClassFromWH(): ?int
    {
        return $this->subClassFromWH;
    }

    public function setSubClassFromWH(int $subClassFromWH): self
    {
        $this->subClassFromWH = $subClassFromWH;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Loot[]
     */
    public function getLoots(): Collection
    {
        return $this->loots;
    }

    public function addLoot(Loot $loot): self
    {
        if (!$this->loots->contains($loot)) {
            $this->loots[] = $loot;
            $loot->setItem($this);
        }

        return $this;
    }

    public function removeLoot(Loot $loot): self
    {
        if ($this->loots->contains($loot)) {
            $this->loots->removeElement($loot);
            // set the owning side to null (unless already changed)
            if ($loot->getItem() === $this) {
                $loot->setItem(null);
            }
        }

        return $this;
    }

    public function getNameDe(): ?string
    {
        return $this->name_de;
    }

    public function setNameDe(?string $name_de): self
    {
        $this->name_de = $name_de;

        return $this;
    }

    public function getInventorySlot(): ?int
    {
        return $this->inventorySlot;
    }

    public function setInventorySlot(?int $inventorySlot): self
    {
        $this->inventorySlot = $inventorySlot;

        return $this;
    }

    public function getZone(): ?Zone
    {
        return $this->zone;
    }

    public function setZone(?Zone $zone): self
    {
        $this->zone = $zone;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    public function getAbbreviation()
    {
        $shortName = [];
        $parts = explode(' ', $this->name);
        foreach ($parts as $part) {
            $shortName[] = substr($part, 0, 1);
        }
        return implode('', $shortName);
    }

    public function getHidden(): ?bool
    {
        return $this->hidden;
    }

    public function setHidden(bool $hidden): self
    {
        $this->hidden = $hidden;

        return $this;
    }
}

templates/macros/bis.html.twig
{% macro checkbox(label, name, value, filters) %}
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="{{ name }}{{ value }}" name="f[{{name}}][{{ value }}]" value="1" {% if filters[name][value] is defined %} checked="checked"{% endif %}>
        <label class="form-check-label" for="{{ name }}{{ value }}">{{ label|raw }}</label>
    </div>
{% endmacro %}

templates/macros/groupbuilder.html.twig
{% macro raidGroup(raidGroup, groupId) %}
    {% if raidGroup.setup.groups[groupId] is defined %}
        {% for player in raidGroup.setup.groups[groupId] %}
            <li
                    class="groupbuilder-item-player class-{{ player.class }} {% if player.twink == true %}twink{% endif %}"
                {% if player.account is not null %}
                    data-account="{{ player.account.id }}"
                {% endif %}
                    data-character="{{ player.id }}"
                    data-spec="{{ player.metaSpec }}"
                    data-class="{{ player.class }}"
            >
                <i class="spec"><img src="/assets/icons/spec_{{ player.spec }}.jpg" width="18"></i>
                <small>{{ player.name }}</small>
            </li>
        {% endfor %}
    {% endif %}
{% endmacro %}

templates/macros/macros.html.twig
{% macro itemicon(slot, slotNumber, priority, wowheaddomain, size='small', highlight='true') %}
    {% if slot[slotNumber][priority] is defined and slot[slotNumber][priority] is not null %}
        {% if slot[slotNumber][priority].hasItem %}
            <div class="bis-list-icon {% if highlight == 'true' %}hasitem{% endif %} bis-icon-{{ size }}">
                <a href="#" data-wowhead="item={{ slot[slotNumber][priority].item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="{{size}}"></a>
            </div>
        {% else %}
            <div class="bis-list-icon missesitem bis-icon-{{ size }}">
                <a href="#" data-wowhead="item={{ slot[slotNumber][priority].item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="{{size}}"><img alt="" class="low-contrast-icon" src="/assets/icons/items/{{slot[slotNumber][priority].item.icon }}-{{ size }}.png"> </a>
            </div>
        {% endif %}
    {% else %}
        <div class="bis-list-icon blank bis-icon-{{ size }}">
&nbsp;
        </div>
    {% endif %}
{% endmacro %}

{% macro itemiconAbbreviation(slot, slotNumber, priority, wowheaddomain, size='small') %}
    {% if slot[slotNumber][priority] is not null %}
        {% if slot[slotNumber][priority].hasItem %}
            <a href="#" data-wowhead="item={{ slot[slotNumber][priority].item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="{{size}}">{{ slot[slotNumber][priority].item.abbreviation }}</a>
        {% else %}
            <a href="#" data-wowhead="item={{ slot[slotNumber][priority].item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="{{size}}" style="color:#444444 !important;">{{ slot[slotNumber][priority].item.abbreviation }}</a>
        {% endif %}
    {% else %}
        <div class="bis-list-icon blank bis-icon-{{ size }}">
            &nbsp;
        </div>
    {% endif %}
{% endmacro %}

{% macro itemDisplay(priority, bisEntry, slotId, character, wowheaddomain) %}
    <div class="card mt-0">
        <div class="card-body">
            <h5 class="card-title">
                {% if priority == 1 %}
                  Best
                {% elseif priority == 2 %}
                  Option
                {% elseif priority == 3 %}
                  Best #2
                {% elseif priority == 4 %}
                    Option #2
                {% endif %}
            </h5>
            {% if bisEntry is not null %}
                <div class="bis-list-remove">
                    <a class="bis-list-remove-button" href="{{ path('delete_bis', {bis: bisEntry.id, charId: character, slot: slotId}) }}"><i class="fa fa-window-close"></i></a>
                </div>
            {% endif %}
            {% if bisEntry is not null %}
                <div class="item-view-with-item">
                    <div class="bis-list d-flex justify-content-between">
                        <div class="bis-list-iconx">
                            <span class="guildbank-item-icon">
                                <a href="#" data-wowhead="item={{ bisEntry.item.id }}&amp;domain={{wowheaddomain}}" data-wh-icon-size="medium"></a>
                            </span>
                        </div>
                    </div>
                    <div class="bis-list-name">
                        <p>{{ bisEntry.item.name }}</p>
                    </div>
                    <div class="custom-control custom-switch">
                        <input type="hidden" name="bisItem[{{ priority }}][{{ bisEntry.item.id }}][hasItem]" value="0">
                        <input type="checkbox" class="custom-control-input" id="customSwitch_{{ priority }}" name="bisItem[{{ priority }}][{{ bisEntry.item.id }}][hasItem]" {% if bisEntry.hasItem %} checked="checked"{% endif %}>
                        <label class="custom-control-label" for="customSwitch_{{ priority }}">has Item</label>
                    </div>
                </div>
            {% else %}
                <div class="item-view-without-item">
                    <select type="text" class="form-control typeahead" id="autocomplete_{{ priority }}" name="bisItem[{{ priority }}][itemId]" style=""></select>
                </div>
            {% endif %}
        </div>
    </div>
{% endmacro %}

{% macro bisSelection(character, slot, activeSlot, slotUtility, bisItems, wowheaddomain) %}
    {% import _self as itemIcons %}
    <li class="list-group-item {% if slot == activeSlot %} active{% endif %}">
        <div class="d-flex justify-content-between">
            <div class="p-2 bd-highlight">
                <a class="btn btn-outline-primary btn-block" title="{{ slotUtility.slotName(slot)}}" href="{{ path('character_bislist', {'charId': character, 'slotId': slot}) }}">{{ slotUtility.slotName(slot)}}</a>
            </div>
            <div class="p-2 bd-highlight d-flex">
                <table class="table table-sm table-borderless">
                    <tr>
                        <td>P1</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 1, wowheaddomain, 'medium') }}</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 2, wowheaddomain, 'medium') }}</td>
                        {% if slot == 11 or slot == 12 %}
                            <td>{{ itemIcons.itemicon(bisItems, slot, 3, wowheaddomain, 'medium') }}</td>
                            <td>{{ itemIcons.itemicon(bisItems, slot, 4, wowheaddomain, 'medium') }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>P2</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 21, wowheaddomain, 'medium') }}</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 22, wowheaddomain, 'medium') }}</td>
                        {% if slot == 11 or slot == 12 %}
                            <td>{{ itemIcons.itemicon(bisItems, slot, 23, wowheaddomain, 'medium') }}</td>
                            <td>{{ itemIcons.itemicon(bisItems, slot, 24, wowheaddomain, 'medium') }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>P3</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 31, wowheaddomain, 'medium') }}</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 32, wowheaddomain, 'medium') }}</td>
                        {% if slot == 11 or slot == 12 %}
                            <td>{{ itemIcons.itemicon(bisItems, slot, 33, wowheaddomain, 'medium') }}</td>
                            <td>{{ itemIcons.itemicon(bisItems, slot, 34, wowheaddomain, 'medium') }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>P4</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 41, wowheaddomain, 'medium') }}</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 42, wowheaddomain, 'medium') }}</td>
                        {% if slot == 11 or slot == 12 %}
                            <td>{{ itemIcons.itemicon(bisItems, slot, 43, wowheaddomain, 'medium') }}</td>
                            <td>{{ itemIcons.itemicon(bisItems, slot, 44, wowheaddomain, 'medium') }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>P5</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 51, wowheaddomain, 'medium') }}</td>
                        <td>{{ itemIcons.itemicon(bisItems, slot, 52, wowheaddomain, 'medium') }}</td>
                        {% if slot == 11 or slot == 12 %}
                            <td>{{ itemIcons.itemicon(bisItems, slot, 53, wowheaddomain, 'medium') }}</td>
                            <td>{{ itemIcons.itemicon(bisItems, slot, 54, wowheaddomain, 'medium') }}</td>
                        {% endif %}
                    </tr>
                </table>
            </div>
        </div>
    </li>
{% endmacro %}

{% macro eventSignup(event, account) %}
    <table class="table table-striped">
        <tr>
            <th>Status</th>
            <th>{% trans %}Character{% endtrans %}</th>
            <th>{% trans %}Actions{% endtrans %}</th>
        </tr>
    {% for toon in account.characters %}
        <tr>
            {% set status = 'question' %}
            {% for signup in event.signups %}
                {% if signup.playerName.id == toon.id %}
                    {% if signup.signedUp == 1 %}
                        {% set status = 'check' %}
                    {% elseif signup.signedUp == 2 %}
                        {% set status = 'times' %}
                    {% endif %}
                {% endif %}
            {% endfor %}
            <td><i class="fa fa-{{status}}"></i></td>
            <td>{{ toon.name }}</td>
            <td>
                <div class="btn-group" role="group">
                    <a href="{{ path('raid_signupforraid', {'characterId': toon.id, 'eventId': event.id}) }}" class="btn btn-success"><i class="fa fa-check"></i></a>
                    <a href="{{ path('raid_signoutforraid', {'characterId': toon.id, 'eventId': event.id}) }}" class="btn btn-danger"><i class="fa fa-times"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
    </table>
    <small>{% trans %}If you do not want to raid with one of your twinks, but will attend with a main character, don't "cancel" with the twink{% endtrans %}</small>
{% endmacro %}

{% macro professions(skill) %}
    {% set percentage =  (skill / 375)*100|round%}
    {% set color = 'bg-secondary' %}
    {% if skill < 100 %}
        {% set color = 'bg-danger' %}
    {% elseif skill < 200 %}
        {% set color = 'bg-warning' %}
    {% elseif skill < 374 %}
        {% set color = 'bg-info' %}
    {% elseif skill > 374 %}
        {% set color = 'bg-success' %}
        {% set percentage = 100 %}
    {% endif %}
    <div class="progress">
        <div class="progress-bar {{ color }}" role="progressbar" style="width: {{ percentage }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{{ skill }}</div>
    </div>
{% endmacro %}

{% macro tradeskills(skillId, skill) %}
    {% if skillId > 0 %}
        <div class="tradeskill">
            <div class="tradeskill-image">
                <img src="{{ asset('assets/icons/tradeskills/tradeskill_'~skillId~'.png') }}" alt="{{ skill }}" title="{{ skill }}">
            </div>
            <div class="tradeskill-progress">
                {% set percentage =  (skill / 375)*100|round%}
                {% set color = 'bg-secondary' %}
                {% if skill < 100 %}
                    {% set color = 'bg-danger' %}
                {% elseif skill < 200 %}
                    {% set color = 'bg-warning' %}
                {% elseif skill < 374 %}
                    {% set color = 'bg-info' %}
                {% elseif skill > 374 %}
                    {% set color = 'bg-success' %}
                    {% set percentage = 100 %}
                {% endif %}
                <div class="progress" style="height:5px">
                    <div class="progress-bar {{ color }}" role="progressbar" style="width: {{ percentage }}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    {% endif %}
{% endmacro %}

{% macro signedUpCheckBox(signUps, character, event, status) %}
    {% if signUps[character.id][event.id] is defined %}
        {% if signUps[character.id][event.id] == status %}
            checked
        {% endif %}
    {% endif %}
{% endmacro %}

{% macro tableHighLight(signUps, event, characters) %}
    {% set class = 'table-danger' %}
    {% for character in characters %}
        {% if signUps[character.id][event.id] is defined %}
            {% if signUps[character.id][event.id] == 1 %}
                {% set class = 'table-success' %}
            {% elseif signUps[character.id][event.id] == 2 %}
                {% set class = 'table-dark' %}
            {% else %}
                {% set class = 'table-danger' %}
            {% endif %}
        {% endif %}
    {% endfor %}
    {{ class }}
{% endmacro %}

{% macro bisProgressBar(bisList, phaseId) %}
    {% set total = 0 %}
    {% set has = 0 %}
    {% if phaseId == '' %}
        {% set startPriority = 0 %}
        {% set endPriority = 5 %}
    {% else %}
        {% set startPriority = phaseId * 10 %}
        {% set endPriority = (phaseId * 10 ) + 5 %}
    {% endif %}
    {% for slot in bisList %}
        {% for priority, entry in slot %}
            {% if 'max' not in priority %}

                {% if priority > startPriority and priority < endPriority %}
                    {% set total = total + 1 %}
                    {% if entry.hasItem == true %}
                        {% set has = has + 1 %}
                    {% endif %}
                {% endif %}

            {% endif %}
        {% endfor %}
    {% endfor %}
    {% if total == 0 %}
        {% set percentage = 100 %}
    {% else %}
        {% set percentage = (has/total)*100 %}
    {% endif %}
    <div class="progress">
        <div class="progress-bar bg-success" role="progressbar" style="width: {{ percentage }}%;" aria-valuenow="{{ percentage }}" aria-valuemin="0" aria-valuemax="100">{{ has }}/{{ total }}</div>
{#        <div class="progress-bar" role="progressbar" style="width: {{ 100 - percentage }}%;" aria-valuenow="{{ 100 - percentage }}" aria-valuemin="0" aria-valuemax="100"></div>#}
    </div>
{% endmacro %}

templates/macros/questheads.html.twig
{% macro questhead(value) %}
    {% if value == 0 %}
        <i class="fa fa-lg fa-skull text-danger"></i>
    {% elseif value == 1 %}
        <i class="fa fa-lg fa-times-circle text-danger"></i>
    {% elseif value == 2 %}
        <i class="fa fa-lg fa-exclamation-circle text-warning"></i>
    {% elseif value == 3 %}
        <i class="fa fa-lg fa-check-circle text-success"></i>
    {% else %}
        wtf?
    {% endif %}
{% endmacro %}